/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BotDetailsModal: typeof import('./blocks/marketplace/BotDetailsModal.vue')['default']
    Button: typeof import('./components/Button.vue')['default']
    CreateListingModal: typeof import('./blocks/marketplace/CreateListingModal.vue')['default']
    Icon: typeof import('./components/Icon.vue')['default']
    Input: typeof import('./components/Input.vue')['default']
    Menu: typeof import('./blocks/Menu.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    Navbar: typeof import('./blocks/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./blocks/Sidebar.vue')['default']
    UserMenu: typeof import('./blocks/UserMenu.vue')['default']
  }
}
